version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    environment:
      XDEBUG_MODE: "debug"
      XDEBUG_CONFIG: "client_host=host.docker.internal"

  staging.php:
    container_name: staging.php
    build: php
    volumes:
      - ./:/app
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"